language: generic

cache:
    directories:
        - $HOME/.stack

os:
    - osx
    - linux

addons:
    apt:
        packages:
            - libgmp-dev

before_install:
    # Download and unpack the stack executable
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - if [ $TRAVIS_OS_NAME = linux ]; then travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; else travis_retry curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xf --strip-components=1 -C ~/.local/bin '*/stack'; fi

install:
    # Build dependencies
    - stack --no-terminal --install-ghc test --only-dependencies

script:
    - stack --no-terminal test --no-haddock-deps
