language: generic
cache:
    directories:
        - "$HOME/.stack"
os:
    - osx
    - linux
addons:
    apt:
        packages:
            - libgmp-dev
before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - if [ $TRAVIS_OS_NAME = linux ]; then travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz
      | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; else travis_retry
      curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar x --strip-components=1
      -C ~/.local/bin '*/stack'; fi
install:
    - stack --no-terminal --install-ghc test --only-dependencies
script:
    - stack build --copy-bins --test --no-terminal --local-bin-path ./bin --no-haddock-deps
before_deploy:
    - if [ $TRAVIS_OS_NAME = linux ]; then mv ./bin/river ./bin/river-linux; else mv ./bin/river
      ./bin/river-osx; fi
deploy:
    - provider: releases
      skip_cleanup: true
      api_key:
          secure: HG6xtNCjWxdOSmXJUR+zDU+kCJoSFxrW9iNNnu5/AporIcoYSXFdW7lNvk1piPJUnfun2F2F2/gECqru1H06INrU23IwICp+RuDYU26IwK8JFauUvMAwWlOqVLBekN+U9yC/LvIuz1f9kUowGUey7oWU8/42fYaZP7y2PnvyGrKJvUBD3eHjKWLOkXZNUmU9+WAjTNsm5+ahSL3OQaNZ2EdQSetYV6JKwqfyeooQEVgNUQgpEHl4GzKIFf8Bfsf75/aw8stG8H2PFGAJaKxBqwnW1A8QWh6HNQNlifUwcnwACydEmUX0XbNDPsjhxXfT6uISMhFlCt/0j4t5tnFyDOVGWlABcCyzg1aVXYLV2clnOj35ChAYwbBYe8aYRsQn8jxzGSNO6zA9yxrR7tdKbvyxlnnI0AIlCdXHGyc6Gr43nIaM9qpznsFWSm9SobXFjnQG5Ig2zx8aa7h366DIKGBJaLHLYZBCyEPod0UizGuncBQy0x85b58766pH7lorrkbbDRyuxflVGjtUGJrN6WHnm6jpG22FvjNjMBzj9dFb3sxd99vEIiOXLQWaGipnouab4bQffDg2T0TB5lQfbJh+3LdjmVX1hIPj3tx649oTPjifQN1wkjFZHuqnrWd2H/Sgc+sRelB8oykX54RZwwDn53GsJeYEtyrvCbKcZYQ=
      file:
          - "./bin/river-linux"
          - "./bin/river-osx"
      on:
          tags: true
          repo: DerekMaffett/river
          branch: master

    - provider: npm
      email: derekgmaffett@gmail.com
      api_key:
          secure: dSjdcHj7H4AKsFreHOtsbAzWirmrlXrK51mPAfb5QZRFvOeCcay9NHN0jc/GSBC7M01QRLvHF/H0fk+Dpo77p7TVSUOwhbfKf07Tp3NCjJdIVvUFrVAMh2gkG021JapNHyOd7ehU/pOB0PZPUl/Gd0W2zeEwZGg+yYREYaIdL7Vd4uEf6dQjYuYUD6uWuJNmU4uPW4hmNPWdDj+QFpMRuho2E9DG5cgErB+AAMzAMfKZVn+hV4KisbBvZeQ0N0iyWuU/0n11YOJDbQPC5xMAY1MOaScdSjr6EkCRC7NZ6ZjbSKKs352BN/lvurDkzs7OqnHlne3eYLcpNqF7begUGHQ0KsMjuywACQv41ovhQA2PQzjKrMwc0mrQRuTNIg7uD2CC7LkCy8t7JzRRIn9oefiD82aeJNDqCnRWdaYXeeIOvVXCZ+6PnHmBQltZFZ2gWEnwBBfCz2Malw4a4FqMWXcYQMAA1Z18Rf38lKiMk4RQ3oHIoWH3CL7vY8DIlM0c9BzOvETzfUsIeG3ribyNcS9xUivkQ27BX9m7lwcmgIRhMz8paskPPwFZBbnCrB2PDe89V0+Cioei9CuY6co0FdVV21rN1wYlP7q3iiguKSrc1AUqvKNFZ//54Ioh+e8xQb8DFV2a451ZRYOQMTctF+GriRdWd4HboDILSUFDm4k=
      on:
          all_branches: true
