language: generic
os:
    - osx
    - linux
before_install:
    - curl https://nixos.org/releases/nix/nix-2.2.1/install | sh
    - ". ~/.nix-profile/etc/profile.d/nix.sh"
install:
    - git submodule update --init
    - echo "1" | reflex-platform/try-reflex || echo "just needed the binary caches..."
script:
    - nix-env -i awscli
    - nix-build
    - result/bin/river-test
    - aws s3 cp result/bin/river s3://river-dist/$TRAVIS_BUILD_NUMBER/$TRAVIS_OS_NAME/river
jobs:
    include:
        - stage: deploy
          os: linux
          before_install:
              - sudo apt-get install awscli
          install:
              - aws s3 mv s3://river-dist/$TRAVIS_BUILD_NUMBER/linux/river ./bin/river-linux
              - aws s3 mv s3://river-dist/$TRAVIS_BUILD_NUMBER/osx/river ./bin/river-osx
              - aws s3 rm --recursive s3://river-dist/$TRAVIS_BUILD_NUMBER/
          script: true
          deploy:
              - provider: releases
                api_key:
                    secure: HG6xtNCjWxdOSmXJUR+zDU+kCJoSFxrW9iNNnu5/AporIcoYSXFdW7lNvk1piPJUnfun2F2F2/gECqru1H06INrU23IwICp+RuDYU26IwK8JFauUvMAwWlOqVLBekN+U9yC/LvIuz1f9kUowGUey7oWU8/42fYaZP7y2PnvyGrKJvUBD3eHjKWLOkXZNUmU9+WAjTNsm5+ahSL3OQaNZ2EdQSetYV6JKwqfyeooQEVgNUQgpEHl4GzKIFf8Bfsf75/aw8stG8H2PFGAJaKxBqwnW1A8QWh6HNQNlifUwcnwACydEmUX0XbNDPsjhxXfT6uISMhFlCt/0j4t5tnFyDOVGWlABcCyzg1aVXYLV2clnOj35ChAYwbBYe8aYRsQn8jxzGSNO6zA9yxrR7tdKbvyxlnnI0AIlCdXHGyc6Gr43nIaM9qpznsFWSm9SobXFjnQG5Ig2zx8aa7h366DIKGBJaLHLYZBCyEPod0UizGuncBQy0x85b58766pH7lorrkbbDRyuxflVGjtUGJrN6WHnm6jpG22FvjNjMBzj9dFb3sxd99vEIiOXLQWaGipnouab4bQffDg2T0TB5lQfbJh+3LdjmVX1hIPj3tx649oTPjifQN1wkjFZHuqnrWd2H/Sgc+sRelB8oykX54RZwwDn53GsJeYEtyrvCbKcZYQ=
                skip_cleanup: true
                file:
                    - "./bin/river-linux"
                    - "./bin/river-osx"
                on:
                    tags: true
                    repo: DerekMaffett/river
              - provider: npm
                email: derekgmaffett@gmail.com
                skip_cleanup: true
                api_key:
                    secure: dSjdcHj7H4AKsFreHOtsbAzWirmrlXrK51mPAfb5QZRFvOeCcay9NHN0jc/GSBC7M01QRLvHF/H0fk+Dpo77p7TVSUOwhbfKf07Tp3NCjJdIVvUFrVAMh2gkG021JapNHyOd7ehU/pOB0PZPUl/Gd0W2zeEwZGg+yYREYaIdL7Vd4uEf6dQjYuYUD6uWuJNmU4uPW4hmNPWdDj+QFpMRuho2E9DG5cgErB+AAMzAMfKZVn+hV4KisbBvZeQ0N0iyWuU/0n11YOJDbQPC5xMAY1MOaScdSjr6EkCRC7NZ6ZjbSKKs352BN/lvurDkzs7OqnHlne3eYLcpNqF7begUGHQ0KsMjuywACQv41ovhQA2PQzjKrMwc0mrQRuTNIg7uD2CC7LkCy8t7JzRRIn9oefiD82aeJNDqCnRWdaYXeeIOvVXCZ+6PnHmBQltZFZ2gWEnwBBfCz2Malw4a4FqMWXcYQMAA1Z18Rf38lKiMk4RQ3oHIoWH3CL7vY8DIlM0c9BzOvETzfUsIeG3ribyNcS9xUivkQ27BX9m7lwcmgIRhMz8paskPPwFZBbnCrB2PDe89V0+Cioei9CuY6co0FdVV21rN1wYlP7q3iiguKSrc1AUqvKNFZ//54Ioh+e8xQb8DFV2a451ZRYOQMTctF+GriRdWd4HboDILSUFDm4k=
                on:
                    tags: true
                    repo: DerekMaffett/river
env:
    global:
        - secure: bKU+4ZK6soScIk38o5eQGMAu1Musg0/IWm4IffZ42Dp98ttQs/X429whYaYGqq38VuFqOfms9mRrwjGqQUQIJAzJHa5zeb6vYHSJhLOTPx+Qi46Hq9mQDVci91MGHabt2K1Xz3MeAt7f8u/sH0r27bHyPCjrhLgCvmOp4Pjnqva9zATOYxLfvo7nK1Wqcv4kobPU3RiIi6iQ6ebKX5IqvjhlyOWvuLOTYVabTdtCFgXEyvm1omcLuyz9ssie1p8vidZbwfpDP7eybrol2WMkN9I8aG6ON1/gpm4QlgzV8MsI0R4f0Kc39mVJjHFGne6MOuhG8iik15eP246e+KqdnOzacNMiFLsNHu4gRgR7kZSMqV5CkCmTMCKZ8Y37u3MIYZDGkaYfKh1yq7NhQd0sMP6nFDiYlBst+bVvF1FoPxQ2El8kM2QDnRnc8CsNUUEsp3co1VDVA+apPQPmCrY1gX9KQSDAnCsZDMrEuETqoO3GGk7WYjr2sZb4bFtIHJZnjZPB/GtoCFWOSfyqMcwfJ0eYo+l3VDpf36D3cFqnoEV2a/LP+xSedoQCll23GsB1ZkybXG1tqRlFZSRhArPQfgUFS17NLf+OA2Pe9FsRJ3LBuufz9j3BxdmKzYTMUulDBMO3rLoAW2DQ5Rx6yIDdvzT8MWDYBvTWqSpTFpDZPws=
        - secure: g4ZxOuPSPAyshTaQcr7PpS13nflvr5LJtYUr7xgk3UNBdWBMWbolfnmX9DrD+MOoYCEMQ9/kqBg/wF2VaqrE/fpHDDg8WPyH0tA0Qr0lyjmOIR+lQYaaGYXEgQQQwrOOLoX1paD7zGs3th+ujawpkgPNxrKIlwSJfG3EX2Z/X6Uyl+5zrymQi1b0B7jUQXC/B1ie/KN3f3+E4R0HHZwxN32P5OTXOhfdt8yt+sDclQUNepYjD4aoe5dU4QcSq64spBO5z/xhJWFWiO5nfyMYbI72cwPwsFXfYjApFdvDOrJHa4jtqAi8TxpDfFif1hsrcU22qdNkrVsRJQWG+FuzgMuLd5XoE1BjY0yu00nwqokem1aEns1XWmv/TT7i3VxDIw4a4J+K4jKLV5VAzfv0AYf8oB8C7lWlNnqQoUvZGRdSeQ8VVvyGjSjWr7T2fneJoEVM7iyRyD7aNlP+CpXMZ20NhQouVawNa8YRx6eaIDr2KLIbv0HrIGgda+ELrAYgH2E3QGPqyMaqEyuF609DME/7G/09IL7j1iWx0i3ypzQzqD747qr+hyfgYaJv60jo11Z7YuVaDJn3xKldny9Wy3ASw/Sf0KSG7oeCk/Ld2TlDih5qL4v50+QBoMciB2O8I+wSYlqyLoJ+zc6OJew/Vip+LY2ClMWUu+4PejeOAaA=
        - secure: WPO0whusO3RievPX4OpPZ6lNEqEJHMIXzeejV9zrFFlKVYaHH4kDi53koY+vosN1+7nEaI6+SR1NUwQlPZzf/dYNS5pL8g6jWzdAlYQ8Pbfk8WaxFZGs95nfAFf39LM7bLMio99Ck0sxlQ2L5mJLjFZFYlTfdN2sDl/P6I0fH8qWqGQoCKk7ayGH5qtUVtB1OjEzWSRkwVDsWa4xbMK5U6bE6hMXSiu0lczWi1OQ4ykzJAoxt2BumRgHo3ZJWU7MzS69nhNqKfGbGwDooTr3J2XdNiFcQj6/lMWvcKRUlyvArRaHajq5W8oXclZ0xZOsDFHn1FIJH3i9C9znfi5/dHzhVEyUOwr2gP6iuQXp905DICJIk6K9J4wYYpXsiiFmfuNbHVWSlVhrsrnaHh2q52alBW5dsstE6+pracDnm4AZtNoUabqOSwR1JFIFNqIrrr7yhZW4afl94hkdhY5zaOLuZmJRKdEc2HwPuk1fe6jrVaOJCTXET7aO7IKSB9ARpWyJskQsHK/Mb8clxNMSMBRZFEjovDWYBmfvF45nQatvlw1wcp+MJBn/Y0Fnk3lc7/P3+K24iSinnXlbeqLH0XO3L58AQnCgO4DoX6pqVgdFGYGiFfti9DddDt7ssU2qa8pA8O95t46yuWhhm9CImIOyz1Ny4zFQP23qgU67p7o=
