name: river
version: 0.1.0.0
github: "DerekMaffett/river"
license: MIT
author: "Derek Maffett"
maintainer: "derekgmaffett@gmail.com"
copyright: "2018 Derek Maffett"

extra-source-files:
    - README.md
    - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/river#readme>

dependencies:
    - base >= 4.7 && < 5
    - split
    - req
    - directory
    - aeson
    - aeson-pretty
    - vector
    - text
    - bytestring
    - process
    - typed-process
    - optparse-applicative
    - unordered-containers
    - containers
    - hslogger
    - mtl
    - safe
    - parsec
    - haskeline
    - graphql
    - safe-exceptions

library:
    source-dirs:
        - core

default-extensions:
    - OverloadedStrings
    - LambdaCase
    - ExistentialQuantification
    - RecordWildCards
    - NamedFieldPuns
    - DuplicateRecordFields
    - DeriveGeneric
    - DeriveAnyClass
    - RecursiveDo
    - ScopedTypeVariables
    - TemplateHaskell
    - FlexibleContexts

executables:
    river:
        main: Main.hs
        source-dirs: cli
        # cc-options: -static
        # ld-options: -static -pthread
        ghc-options:
            - -threaded
            - -rtsopts
            # - -optl-static
            # - -optl-pthread
            - -with-rtsopts=-N
            - -Wall
        dependencies:
            - river

    # river-gui:
    #     main: Main.hs
    #     source-dirs: gui
    #     # cc-options: -static
    #     # ld-options: -static -pthread
    #     ghc-options:
    #         - -threaded
    #         - -rtsopts
    #         # - -optl-static
    #         # - -optl-pthread
    #         - -with-rtsopts=-N
    #         - -Wall
    #     dependencies:
    #         - river
    #         - reflex
    #         - reflex-dom
    #         - file-embed
    #         - data-default-class

    river-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - river
            - hspec
            - QuickCheck

    river-integration-tests:
        main: IntegrationSpecs.hs
        source-dirs: integration-tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - river
            - hspec
            - QuickCheck
